x-setup: &default_setup
  image: ${COMPOSE_PROJECT_NAME}-app
  build:
    context: .
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
      - "PROXY_SERVER=${PROXY_SERVER}"
  environment:
    - "UID=${UID:-1000}"
    - "GID=${GID:-1000}"
    - LANG=en_US.UTF-8
  user: "${UID:-1000}:${GID:-1000}"
  volumes: &base_volume
    - .:/home/ubuntu/apps/app
    - ${HOME}/.ssh:/home/ubuntu/.ssh:ro
    - ${HOME}/.gitconfig:/home/ubuntu/.gitconfig:ro

services:
  setup_base: &setup_base
    <<: *default_setup
    command: bash --login -c "ls"
